# Generated by Django 3.0.3 on 2020-04-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avizier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_post',
            new_name='date',
        ),
    ]
