# Generated by Django 3.0.3 on 2020-05-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avizier', '0002_auto_20200429_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='event'),
        ),
    ]
