# Generated by Django 3.0.3 on 2020-05-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avizier', '0005_auto_20200520_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
